openapi: 3.2.0
info:
  title: Arccos On-Course Data Courses API
  version: '1'
  description: '## Introduction

    Welcome to The On-Course Data API, powered by Arccos.'
tags:
- name: Courses
paths:
  /v5/courses:
    get:
      summary: Search Courses
      tags:
      - Courses
      operationId: handle_search_courses.get./v5/courses
      parameters:
      - in: query
        name: limit
        description: maximum number of results to get
        required: false
        schema:
          type: integer
      - in: query
        name: offset
        description: number of results to get per request
        required: false
        schema:
          type: integer
      - in: query
        name: name
        description: Search by partial course name
        required: false
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCoursesResponse'
  /v5/courses/{courseId}:
    get:
      summary: Get One Course
      tags:
      - Courses
      operationId: handle_get_one_course.get./v5/courses/{courseId}
      parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOneCourseResponse'
  /v5/courses/{courseId}/versions/{courseVersion}:
    get:
      summary: Get One Course Version
      tags:
      - Courses
      operationId: handle_get_one_course_version.get./v5/courses/{courseId}/versions/{courseVersion}
      parameters:
      - name: courseId
        in: path
        required: true
        schema:
          type: string
      - name: courseVersion
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCoursesResponse'
components:
  schemas:
    PagedResponseHelper:
      properties:
        paging:
          properties:
            limit:
              title: PagedResponseHelper.paging.limit
              type: number
            offset:
              title: PagedResponseHelper.paging.offset
              type: number
            previous:
              title: PagedResponseHelper.paging.previous
              type: string
            next:
              title: PagedResponseHelper.paging.next
              type: string
          required:
          - limit
          - offset
          additionalProperties: false
          title: PagedResponseHelper.paging
          type: object
        results:
          items:
            title: PagedResponseHelper.results.[]
          title: PagedResponseHelper.results
          type: array
      required:
      - paging
      - results
      additionalProperties: false
      title: PagedResponseHelper
      type: object
    GetCoursesResponse:
      allOf:
      - $ref: '#/components/schemas/PagedResponseHelper'
      - properties:
          results:
            items:
              $ref: '#/components/schemas/Course'
              title: results.[]
            title: results
            type: array
        required:
        - results
        additionalProperties: false
        type: object
      title: GetCoursesResponse
    Location:
      properties:
        latitude:
          title: Location.latitude
          type: number
        longitude:
          title: Location.longitude
          type: number
      required:
      - latitude
      - longitude
      additionalProperties: false
      title: Location
      type: object
    CourseHole:
      properties:
        holeId:
          title: CourseHole.holeId
          type: number
        mensPar:
          title: CourseHole.mensPar
          type: number
        womensPar:
          title: CourseHole.womensPar
          type: number
      required:
      - holeId
      - mensPar
      - womensPar
      additionalProperties: false
      title: CourseHole
      type: object
    Tee:
      properties:
        teeId:
          title: Tee.teeId
          description: the numeric identifier for the tee. this is unique against the courseId and courseVersion, not globally unique
          type: number
        teeName:
          title: Tee.teeName
          description: the display string for the tee that was played
          type: string
      required:
      - teeId
      - teeName
      additionalProperties: false
      title: Tee
      type: object
    Course:
      properties:
        courseId:
          title: Course.courseId
          type: number
        courseVersion:
          title: Course.courseVersion
          type: number
        name:
          title: Course.name
          type: string
        numberOfHoles:
          title: Course.numberOfHoles
          type: number
        mensPar:
          title: Course.mensPar
          type: number
        womensPar:
          title: Course.womensPar
          type: number
        location:
          $ref: '#/components/schemas/Location'
          title: Course.location
        city:
          title: Course.city
          type: string
        state:
          title: Course.state
          type: string
        country:
          title: Course.country
          type: string
        altitude:
          title: Course.altitude
          type: number
        holes:
          items:
            $ref: '#/components/schemas/CourseHole'
            title: Course.holes.[]
          title: Course.holes
          type: array
        tees:
          items:
            $ref: '#/components/schemas/Tee'
            title: Course.tees.[]
          title: Course.tees
          type: array
      required:
      - courseId
      - courseVersion
      - name
      - numberOfHoles
      - mensPar
      - womensPar
      - location
      - city
      - state
      - country
      - holes
      - tees
      additionalProperties: false
      title: Course
      type: object
    GetOneCourseResponse:
      $ref: '#/components/schemas/Course'
      title: GetOneCourseResponse
  securitySchemes:
    AccessCodeAuth:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            openid: Required for all endpoints that have userId in the path
            arccos/read:users: Grants read users access
            arccos/read:rounds: Grants read rounds access
            arccos/read:clubs: Grants read clubs access
          authorizationUrl: https://signin.arccosgolf.com/login
          tokenUrl: https://api.arccosgolf.com/oauth2/token
    BasicAuth:
      type: http
      scheme: basic
