openapi: 3.2.0
info:
  title: Arccos On-Course Data Users API
  version: '1'
  description: '## Introduction

    Welcome to The On-Course Data API, powered by Arccos.'
tags:
- name: Users
paths:
  /v5/users/{userId}:
    get:
      summary: Get One User
      description: Get details for one user
      tags:
      - Users
      operationId: handle_get_one_user.get./v5/users/{userId}
      security:
      - AccessCodeAuth:
        - arccos/read:users
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOneUserResponse'
components:
  schemas:
    GetOneUserResponse:
      $ref: '#/components/schemas/User'
      title: GetOneUserResponse
    User:
      properties:
        userId:
          title: User.userId
          type: string
        firstName:
          title: User.firstName
          type: string
        lastName:
          title: User.lastName
          type: string
        email:
          title: User.email
          type: string
        stance:
          enum:
          - right
          - left
          title: User.stance
          type: string
        gender:
          enum:
          - male
          - female
          title: User.gender
          type: string
        estimatedHandicap:
          title: User.estimatedHandicap
          type:
          - number
          - 'null'
      required:
      - userId
      - firstName
      - lastName
      - email
      - stance
      - gender
      - estimatedHandicap
      additionalProperties: false
      title: User
      type: object
  securitySchemes:
    AccessCodeAuth:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            openid: Required for all endpoints that have userId in the path
            arccos/read:users: Grants read users access
            arccos/read:rounds: Grants read rounds access
            arccos/read:clubs: Grants read clubs access
          authorizationUrl: https://signin.arccosgolf.com/login
          tokenUrl: https://api.arccosgolf.com/oauth2/token
    BasicAuth:
      type: http
      scheme: basic
