openapi: 3.2.0
info:
  title: Arccos On-Course Data Clubs API
  version: '1'
  description: '## Introduction

    Welcome to The On-Course Data API, powered by Arccos.'
tags:
- name: Clubs
paths:
  /v5/users/{userId}/clubs:
    get:
      summary: Search clubs
      description: Search a users clubs
      tags:
      - Clubs
      operationId: handle_search_clubs.get./v5/users/{userId}/clubs
      security:
      - AccessCodeAuth:
        - arccos/read:clubs
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      - in: query
        name: limit
        description: maximum number of results to get
        required: false
        schema:
          type: integer
      - in: query
        name: offset
        description: number of results to get per request
        required: false
        schema:
          type: integer
      - in: query
        name: status
        description: paired, unpaired, or deleted. defaults to paired.
        required: false
        schema:
          type: string
      - in: query
        name: numberOfShots
        description: number of shots to consider when computing club distances. Valid values are 5, 10, 15, 20, 25, 50, 100. Defaults to 100.
        required: false
        schema:
          type: number
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClubsResponse'
  /v5/users/{userId}/clubs/{clubId}:
    get:
      summary: Get One Club
      tags:
      - Clubs
      operationId: handle_get_one_club.get./v5/users/{userId}/clubs/{clubId}
      security:
      - AccessCodeAuth:
        - arccos/read:clubs
      parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      - name: clubId
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOneClubResponse'
components:
  schemas:
    PagedResponseHelper:
      properties:
        paging:
          properties:
            limit:
              title: PagedResponseHelper.paging.limit
              type: number
            offset:
              title: PagedResponseHelper.paging.offset
              type: number
            previous:
              title: PagedResponseHelper.paging.previous
              type: string
            next:
              title: PagedResponseHelper.paging.next
              type: string
          required:
          - limit
          - offset
          additionalProperties: false
          title: PagedResponseHelper.paging
          type: object
        results:
          items:
            title: PagedResponseHelper.results.[]
          title: PagedResponseHelper.results
          type: array
      required:
      - paging
      - results
      additionalProperties: false
      title: PagedResponseHelper
      type: object
    ClubType:
      title: ClubType
      type: string
    Club:
      properties:
        clubId:
          title: Club.clubId
          type: number
        status:
          enum:
          - paired
          - unpaired
          - deleted
          title: Club.status
          type: string
        make:
          properties:
            id:
              title: Club.make.id
              description: the numerical arccos id of the club's make
              type: number
            name:
              title: Club.make.name
              description: the display string/name of the make
              type: string
          required:
          - id
          - name
          additionalProperties: false
          title: Club.make
          description: the make of the given club. if this property doesn't exist Arccos doesn't have the make information for the club.
          type: object
        model:
          properties:
            id:
              title: Club.model.id
              description: the numerical arccos id of the club's model
              type: number
            name:
              title: Club.model.name
              description: the display string/name of the model
              type: string
          required:
          - id
          - name
          additionalProperties: false
          title: Club.model
          description: the model of the given club. if this property doesn't exist Arccos doesn't have the model information for the club
          type: object
        clubType:
          $ref: '#/components/schemas/ClubType'
          title: Club.clubType
        stats:
          properties:
            distances:
              properties:
                longest:
                  title: Club.stats.distances.longest
                  type: number
                average:
                  title: Club.stats.distances.average
                  type: number
              required:
              - longest
              - average
              additionalProperties: false
              title: Club.stats.distances
              type: object
            normalizedDistances:
              properties:
                longest:
                  title: Club.stats.normalizedDistances.longest
                  type: number
                average:
                  title: Club.stats.normalizedDistances.average
                  type: number
              required:
              - longest
              - average
              additionalProperties: false
              title: Club.stats.normalizedDistances
              type: object
            numberOfShots:
              title: Club.stats.numberOfShots
              type: number
          required:
          - distances
          - normalizedDistances
          - numberOfShots
          additionalProperties: false
          title: Club.stats
          type: object
      required:
      - clubId
      - status
      - clubType
      - stats
      additionalProperties: false
      title: Club
      type: object
    GetClubsResponse:
      allOf:
      - $ref: '#/components/schemas/PagedResponseHelper'
      - properties:
          results:
            items:
              $ref: '#/components/schemas/Club'
              title: results.[]
            title: results
            type: array
        required:
        - results
        additionalProperties: false
        type: object
      title: GetClubsResponse
    GetOneClubResponse:
      $ref: '#/components/schemas/Club'
      title: GetOneClubResponse
  securitySchemes:
    AccessCodeAuth:
      type: oauth2
      flows:
        authorizationCode:
          scopes:
            openid: Required for all endpoints that have userId in the path
            arccos/read:users: Grants read users access
            arccos/read:rounds: Grants read rounds access
            arccos/read:clubs: Grants read clubs access
          authorizationUrl: https://signin.arccosgolf.com/login
          tokenUrl: https://api.arccosgolf.com/oauth2/token
    BasicAuth:
      type: http
      scheme: basic
